<a href="https://colab.research.google.com/github/D2J3D/PrLinAlg_Lab1/blob/main/Practical_Linear_Algebra_Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [245]:
import math
import random
import numpy as np


In [246]:
# setup
custom_alphabet = "й ц у к е н г ш щ з х ъ ф ы в а п р о л д ж э я ч с м и т ь б ю".split(" ")
custom_alphabet.append(" ")
custom_alphabet.sort()

In [247]:
def encrypt_matrix_former(key_word, alphabet):
    m = round(math.sqrt(len(key_word)))  # matrix size
    encrypt_matrix = [[0] * m for i in range(m)]
    j, k = 0, 0
    for i in range(len(key_word)):
        k %= m
        encrypt_matrix[j][k] = alphabet.index(key_word[i])
        if (i + 1) % m == 0:
            j += 1
        k += 1
    return np.array(encrypt_matrix)

In [248]:
def key_word_generator(alphabet, n):
    try:
        random_numbers = list(range(0, len(alphabet)))
        random.shuffle(random_numbers)
        key_word = ""
        for i in range(n):
            key_word += alphabet[random_numbers[i]]
        return key_word

    except ValueError:
        print(f"Не получится задать ключ длины n = {int(math.sqrt(n))}. Выбери меньшее значение n")

In [249]:
def vector_to_text(text_vector, alphabet):
  n, m = text_vector.shape[0], text_vector.shape[1]
  text = ""
  for i in range(n):
    for j in range(m):
      text += alphabet[text_vector[i][j]]
  return text


In [250]:
def mod(column_vector, n):
  for i in range(column_vector.shape[0]):
    column_vector[i] %= n
  return column_vector


In [251]:
def text_to_matrix(text, alphabet, key_word_length):
  n = round(math.sqrt(key_word_length))
  word_matrix = [[0]*n for _ in range(math.ceil(len(text)/n))]
  j, k = 0, 0
  for i in range(len(text)):
    k %= n
    word_matrix[j][k] = alphabet.index(text[i])
    k += 1
    if (i + 1) % n == 0:
      j += 1
  return np.array(word_matrix)




In [252]:
def encrypt_text(encrypt_matrix, text, n, alphabet):
    encrypt_matrix_arr = np.array(encrypt_matrix)
    word_arr = text_to_matrix(text, alphabet, len(encrypt_matrix[0])**2)
    text_vector = np.zeros(shape=(len(word_arr), encrypt_matrix_arr.shape[1]), dtype=int)
    for i in range(word_arr.shape[0]):
        text_vector[i] = mod(np.dot(word_arr[i], encrypt_matrix_arr), n)
    return text_vector

In [253]:
example_key_word = key_word_generator(custom_alphabet, 16)

In [254]:
example_encrypt_matrix = encrypt_matrix_former(example_key_word, custom_alphabet)

In [255]:
print(example_key_word)
print(example_encrypt_matrix)
print(vector_to_text(example_encrypt_matrix, custom_alphabet))
print(text_to_matrix(example_key_word, custom_alphabet, len(example_key_word)))
print()
print(encrypt_text(example_encrypt_matrix, "ботай матан", len(custom_alphabet), custom_alphabet))

щмбсънзжьыларпгэ
[[26 13  2 18]
 [27 14  8  7]
 [29 28 12  1]
 [17 16  4 30]]
щмбсънзжьыларпгэ
[[26 13  2 18]
 [27 14  8  7]
 [29 28 12  1]
 [17 16  4 30]]

[[ 2 25 26 25]
 [27 15 15 25]
 [ 3 26 16  0]]
